# https://commandprompt.com/education/how-to-install-postgresql-using-docker-compose/
version: '3.8'

volumes:
  postgres_db:
    driver: local

services:
  postgres_db:
    image: postgres:latest
    container_name: cwe_statistics_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
